### ISSUE TITLE
Error when trying to extract Allen map

### ISSUE THREAD

**Issue by tjoy20** [jcouto/wfield#6]
Hi Joao,
Thanks so much for wfield. I've been trying to create my own reference space. When I run the prepare_allen_map.ipynb, I get the following error (attached). Any help would be greatly appreciated.

<img width="990" alt="Screen Shot 2021-09-29 at 11 06 53 PM" src="https://user-images.githubusercontent.com/69219166/135397093-a1d22d52-af62-47b1-818d-f64e9c916462.png">

**Comment by jcouto** [comment]
Hi, thanks for finding this! 
It happened because `allen_utils.py` was missing an import.
It is fixed in commit 79886a8 

Could you update and let me know if you still have issues, please? Let me know if you need help updating. I updated also the Pypi package to version 0.2.2a.
Thanks again!

**Comment by tjoy20** [comment]
Thanks a lot, this did it!
